### ISSUE TITLE
Eval throws security errors in Chrome extensions

### ISSUE THREAD

**Issue by guivr** [kristerkari/css-calc-transform#170]
Hi, Krister! First of all, thank you SO MUCH for this library, it's awesome! :)

Now with the new Manifest V3 for Chrome extensions, `eval` is not allowed anymore.

I tried changing the `eval` part into `Function()` but it's also not allowed by Chrome.

I found 2 libraries and 1 snippet that could be useful to stop using eval and also increase the security:
https://github.com/silentmatt/expr-eval
https://github.com/devrafalko/string-math
https://stackoverflow.com/a/47761792
maybe there are other ones as well.

I was going to implement it myself but seems like it would have to also adapt the lines:
```
const MIN_MAX_REPLACEMENT = "Math.$1";
const CLAMP_REPLACEMENT = "Math.max($1, Math.min($2, $3))";
```
since these libraries don't have the `Math.` thing. Maybe it would have to calculate `Math.max` and `Math.min` directly.

**Comment by kristerkari** [comment]
Thanks @guivr !

I was not aware of this limitation. I'll have a look at your suggestions.

**Comment by kristerkari** [comment]
I released a new version that does not use eval. Let me know if this fixes your problem!

https://github.com/kristerkari/css-calc-transform/releases/tag/v1.1.0

**Comment by guivr** [comment]
> I released a new version that does not use eval. Let me know if this fixes your problem!
> 
> https://github.com/kristerkari/css-calc-transform/releases/tag/v1.1.0

You're awesome! Thank you very much 🙏🙌
