### ISSUE TITLE
Transform fails with % + em calculation

### ISSUE THREAD

**Issue by guivr** [kristerkari/css-calc-transform#24]
Hi, Krister! First of all, thank you SO MUCH for this library :)

The transform is currently failing with the calculation:
`calc(10% + 1em)`

Error:
```
SyntaxError: Invalid or unexpected token
    at transform
```

related to line 123:
`var result = eval("(" + currentFormula + ")");`

**Comment by kristerkari** [comment]
@guivr Sorry for not noticing this before. I can create a fix for that :)

**Comment by kristerkari** [comment]
...and to clarify, this is because there is no support for `em` units. It should not be a problem to add support for them though, just need to pass in the parent element's font size.

**Comment by guivr** [comment]
Thanks a lot for this 🙏😍
